# Generated by Django 6.0.3 on 2026-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="subject_code",
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
