# Generated by Django 6.0.3 on 2026-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cie", "0002_remove_student_subject_code_alter_student_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Studentnew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usn", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("cie_marks", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
